# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lionreport', '0002_evaluation_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lioncore.Course', verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='result',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
